language: node_js
node_js:
  - 10
services:
  - docker

install:
  - npm install

script:
  - npm test
  - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .

before_deploy:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script: heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch:
      - master
      - dev
